apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: rke2-downstream-harvester
  namespace: fleet-default # Obligatoire : Turtles écoute dans fleet-default
  labels:
    # Ligne magique : Turtles va importer automatiquement le cluster dans l'UI Rancher dès qu'il sera prêt
    cluster-api.cattle.io/rancher-auto-import: "true"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.244.0.0/16"]
  # Étape A : On lie l'infrastructure à Harvester
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HarvesterCluster
    name: harvester-infra-target
  # Étape B : On lie le Control Plane au moteur RKE2
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: RKE2ControlPlane
    name: rke2-control-plane-target
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HarvesterCluster
metadata:
  name: harvester-infra-target
  namespace: fleet-default
spec:
  # C'est ici que tu cibles ton Harvester physique connu par Rancher
  harvesterClusterRef:
    name: "c-8nwwt"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HarvesterMachineTemplate
metadata:
  name: rke2-sle-micro-template
  namespace: fleet-default
spec:
  template:
    spec:
      vmConfig:
        cpuCount: 4
        memorySize: 8Gi
        imageName: "harvester-public/sle-micro-62" # Ton image d'OS
        networkName: "harvester-public/management" # Ton réseau par défaut (DHCP externe requis)
      # Configuration de tes disques pour isoler /var/lib
      cloudInit:
        userData: |
          #cloud-config
          runcmd:
            - |
              # 1. Formater le second disque vdb en XFS
              mkfs.xfs /dev/vdb
              # 2. Récupérer son UUID et l'ajouter au fstab
              UUID=$(blkid -s UUID -o value /dev/vdb)
              echo "UUID=${UUID} /var/lib xfs defaults,noatime 0 2" >> /etc/fstab
              # 3. Créer le point de montage et monter le disque
              mkdir -p /var/lib
              mount /var/lib
