# 1. Les Identifiants Cloud (Obligatoire pour l'authentification)
apiVersion: provisioning.cattle.io/v1
kind: CloudCredential
metadata:
  name: harvester-creds
  namespace: fleet-default
spec:
  harvesterCredentialConfig:
    clusterId: "c-8nwwt" # Ton Harvester
---
# 2. Le Template de Machine Standard Rancher 2.12
apiVersion: rke-node.cattle.io/v1
kind: HarvesterMachineTemplate
metadata:
  name: rke2-sle-micro-template
  namespace: fleet-default
spec:
  template:
    spec:
      cpuCount: "4"
      memorySize: "8"
      diskBus: virtio
      imageName: "harvester-public/sle-micro-62"
      networkName: "harvester-public/management"
      disks:
        - size: 60
          autoDelete: true
      userData: |
        #cloud-config
        runcmd:
          - |
            mkfs.xfs /dev/vdb
            UUID=$(blkid -s UUID -o value /dev/vdb)
            echo "UUID=${UUID} /var/lib xfs defaults,noatime 0 2" >> /etc/fstab
            mkdir -p /var/lib
            mount /var/lib
---
# 3. La Définition du Cluster RKE2 Standard
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: rke2-downstream-harvester
  namespace: fleet-default
spec:
  kubernetesVersion: v1.31.1+rke2r1
  cloudCredentialSecretName: fleet-default/harvester-creds

  rke2Config:
    chartValues:
      rke2-cilium:
        k8sServiceHost: "127.0.0.1"
        k8sServicePort: 6443

  controlPlaneNodesConfig:
    controlPlaneConfig:
      count: 3
      machineTemplateRef:
        apiVersion: rke-node.cattle.io/v1
        kind: HarvesterMachineTemplate
        name: rke2-sle-micro-template
